name: Publish Templates
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/action@v1
        with:
          publish-templates: true
          base-path-to-templates: ./src
          generate-docs: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
